stages:
  - build
  - release

build:
  stage: build
  image: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/containers/java:sdk-builder
  when: manual
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    spring_profiles_active: build
    NUTANIX_API_URL: https://csp-mock-staging.i.megaport.com/nutanix/v1/direct_connect
    NUTANIX_IAM_URL: https://csp-mock-staging.i.megaport.com/nutanix/api/nutanix/v3/iam/service_token
    NUTANIX_KEY: /workspace/keys/nutanix-production.20180711.key
    NUTANIX_CERT: /workspace/keys/nutanix-production.20180711.crt
  services:
    - name: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/development/megalith:latest
    - name: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/containers/postgres:latest
    - name: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/containers/rabbitmq:latest
    - name: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/networks/megadb-api:latest
    - name: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/development/pricingservice:latest
  only:
    - master
    - /^feature\/.*$/
  tags:
    - k8s
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - .m2/repository/
  artifacts:
    expire_in: 7 days
    paths:
      - target/
  script:
    - sed -i "s/GPG_PASSPHRASE/$GPG_PASSPHRASE/g" /root/.m2/settings.xml
    - echo "$GNUPG" | base64 -d > /root/.gnupg.tar.gz
    - tar -xzf /root/.gnupg.tar.gz -C /root/
    - source ~/.bashrc
    - sleep 300  # wait for megalith bootstrap
    - mvn clean package

maven:
  stage: release
  image: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/containers/java:sdk-builder
  when: manual
  only:
    - master
  tags:
    - k8s
  dependencies:
    - build
  script:
    - sed -i "s/GPG_PASSPHRASE/$GPG_PASSPHRASE/g" /root/.m2/settings.xml
    - echo "$GNUPG" | base64 -d > /root/.gnupg.tar.gz
    - tar -xzf /root/.gnupg.tar.gz -C /root/
    - source ~/.bashrc
    - mvn -U clean deploy -P release -Dmaven.test.skip=true

github:
  stage: release
  image: 073096867023.dkr.ecr.ap-southeast-2.amazonaws.com/containers/ansible:latest
  when: manual
  dependencies: []
  only:
    - master
  tags:
    - k8s
  script:
    # Remove this GitLab CI file
    - echo ".gitlab-ci.yml" >> .gitignore
    - git pull origin master
    - git checkout master
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config user.email
    - git config user.name
    - git add .
    - git commit -m ".gitignore"
    # Push to GitHub
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_PRIVATE_SSH_KEY")
    - mkdir -p ~/.ssh
    - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
    - git remote add github git@github.com:megaport/Java-MegaportAPI.git
    - git push --force github master
